### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jorgenem** [oslocyclotronlab/Qkinz#11]
I just cloned the repo and attempted to build according to the README instructions (qmake Qkinz.pro -> make). However, the make command fails, saying

`In file included from gui/include/mainwindow.h:17:0,
                 from gui/src/mainwindow.cpp:1:
support/include/BatchReader.h:9:20: fatal error: Worker.h: No such file or directory
compilation terminated.
Makefile:472: recipe for target '../build/src/objects/mainwindow.o' failed
make[1]: *** [../build/src/objects/mainwindow.o] Error 1
make[1]: Leaving directory '/home/jorgenem/gitrepos/Qkinz-orig/src'
Makefile:41: recipe for target 'sub-src-make_default' failed
make: *** [sub-src-make_default] Error 2
`

Is it my system or the software that is the problem?

**Comment by vetlewi** [comment]
The problem due to a typo in BatchReader.h
This has been fixed in one of the recent commits.
