### ISSUE TITLE
Stopping power for elements not in table

### ISSUE THREAD

**Issue by fzeiser** [oslocyclotronlab/Qkinz#15]
Trying to calculate the energies for a 240Pu(d,p) experiment. Entering the corresponding values the calculations look unsuspicious. However, in the terminal window where I execute Qkinz, I get following type of errors:

> Element not in table.
> Error retriving variables. Shure element(A,Z) (240, 94) is a valid isotope?
> Element not in table.
> Error retriving variables. Shure element(A,Z) (241, 94) is a valid isotope?

**Comment by fzeiser** [comment]
Asked @vetlewi for what the problem was. Seemingly there is no tabulated stopping power for Pu. It should fallback the to Bethe-Block formula, however it doesn't.

**Comment by fzeiser** [comment]
Feature request: When you fix it, can you also build in an info panel somewhere that shows you whether the program uses tabulated values, or some fitted parameters for the Bethe-Block formula?

**Comment by vetlewi** [comment]
After examination it seems like this is just a warning, the program will in fact fall back on Bethe-Block as it should and the program does the calculations as it should. This is checked in MacOS (see screenshot), could you check if this is the case for linux as well? I'm working on a patch that should make the program more informative such that the user knows that it's not a problem, just that a different model for the stopping-power is used than for elements between 1 and 92.

At some point a settings panel where the user can choose what model to use for the stopping power should be implemented. However it may require a rather large rework of the code base that I don't have time to work on.

![image](https://user-images.githubusercontent.com/5293376/37829836-e72cd3f0-2ea0-11e8-8dd8-f4a59a728db4.png)

**Comment by fzeiser** [comment]
Well, what does "does the calculations as it should" mean? 

I receive the same plot -- due to the warning/error message however, I didn't know how there values were calculated, so how reliable they are. So in other words, I didn't know whether it fell back to some fitted parameters, or suddenly would start to do non-sense.

If I understand you're message correctly, Qkinz does the first, and this is a warning I may live with.
